# Generated by Django 5.1.7 on 2025-03-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='firstname', max_length=20, verbose_name='name')),
                ('lastname', models.CharField(blank=True, default='lastname', max_length=20, verbose_name='surname')),
                ('address', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(default=0, unique=True, verbose_name='phone number')),
            ],
            options={
                'db_table': 'formapp_Customer',
            },
        ),
    ]
