# Generated by Django 5.1.7 on 2025-03-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('school_name', models.CharField(max_length=255)),
                ('standard_class', models.CharField(max_length=50)),
                ('device_used', models.CharField(choices=[('Laptop', 'Laptop'), ('Tablet', 'Tablet'), ('Mobile Phone', 'Mobile Phone'), ('Others', 'Others')], max_length=50)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('State', 'State')], max_length=20)),
            ],
        ),
    ]
