# Generated by Django 5.1.7 on 2025-04-20 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0002_alter_studentinfo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('device', models.CharField(blank=True, max_length=100)),
                ('class_level', models.CharField(blank=True, max_length=50)),
                ('board', models.CharField(blank=True, choices=[('CBSE', 'CBSE'), ('State', 'State')], max_length=50)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
